[package]
name = "code"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
# rand_pcg = "0.3"
# serde = { version = "1.0", features = ["derive"] }
criterion = "0.5"

[[bench]]
name = "dijkstra"
harness = false

